apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "json-exporter.fullname" . }}
  labels:
    {{- include "json-exporter.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "files/config.yml").AsConfig | indent 2 }}
