apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "json-exporter.fullname" . }}
  labels:
    {{- include "json-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "json-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "json-exporter.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
          - name: CONFIG_FILE_PATH
            value: /config/{{ .Values.config.filename }}
          command: ["sh", "-c", "/bin/json_exporter --config.file=$CONFIG_FILE_PATH" ]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: jexporter-port
              containerPort: {{ .Values.service.port }}
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /probe
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /probe
#              port: http
          volumeMounts:
          - name: config
            mountPath: /config/
      volumes:
        - name: config
          configMap:
            name: {{ include "json-exporter.fullname" . }}
