apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "json-exporter.fullname" . }}
  labels:
    {{- include "json-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "json-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "json-exporter.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      initContainers:
        - name: reload-config
          image: busybox:1.28
          volumeMounts:
          - name: modules
            mountPath: /config.d
          - name: config
            mountPath: /config/
          command:
          - "/bin/sh"
          - "-c"
          - |
            cd config.d && \
            for filename in $(ls | grep -E ".y(a|)ml"); do \
              if [ "$filename" == "config.yml" ]; then continue; fi; \
              if grep -q "modules:" "$filename"; then \
                echo "File found: $filename"
                cat "$filename" >> /config/config.yml; \
              fi
            done ; \
            sed -i 's/modules://g' /config/config.yml ; \
            sed -i '1i\modules:' /config/config.yml ; \
            sed -i '/^$/d' /config/config.yml;
            echo "Created config.yml"
      containers:
        - name: {{ .Chart.Name }}
          env:
          - name: CONFIG_FILE_PATH
            value: /{{ .Values.config.filename }}
          command: ["sh", "-c", "/bin/json_exporter --config.file=$CONFIG_FILE_PATH" ]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: jexporter-port
              containerPort: {{ .Values.service.port }}
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /probe
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /probe
#              port: http
          volumeMounts:
          - name: config
            mountPath: /config.yml
            subPath: config.yml
      volumes:
        - name: modules
          configMap:
            name: {{ include "json-exporter.fullname" . }}
        - name: config
          emptyDir: {}
